version: "3"

services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  admin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - 7000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.net
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
